# App
spring.application.name=HomeApplianceStore

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/home_appliance_store
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# Resources
spring.web.resources.static-locations=classpath:/static/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.mvc.hiddenmethod.filter.enabled=true

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
# Development only
spring.liquibase.drop-first=true